[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 15.5

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
# style = "Light"

[font.glyph_offset]
x =  0
y = -2

[font.offset]
x = -1
y = -4

[cursor]
style = "Block"
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

# Useful in MacOs
# [window]
# option_as_alt = "Both"

# Colors (Gruvbox Material Medium Dark)
[colors.primary]
background = '#282828'
foreground = '#d4be98'

# Normal colors
[colors.normal]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#3c3836'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

